name: Mirror Terraform Provider
on:
  push:
    branches:
      - master

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0


      - name: Setup Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.2.1

      - name: Download Core
        run: |
          bin/core.sh terraform.json

      - name: Download Provides
        run: |
          bin/mirror.sh providers/aws.json
          bin/mirror.sh providers/keycloak.json
          bin/mirror.sh providers/random.json
          bin/mirror.sh providers/vault.json

      - name: Deploy mirror to s3 bucket
        env:
          MIRROR_PATH: './mirror'
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 sync ${MIRROR_PATH} ${S3_BUCKET_NAME} --acl public-read