name: Update Terraform Providers
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update Terraform Provider Versions
        run: |
            ls -la

            bin/updater.sh providers/aws.json
            bin/updater.sh providers/keycloak.json
            bin/updater.sh providers/random.json
            bin/updater.sh providers/vault.json

            echo
            cat providers/random.json

      - name: Push changes to repo
        run: |
          #!/bin/sh -e
          MESSAGE="
            Update provider versions
          "
          if ! git diff-index --quiet HEAD; then
            git config --global user.name "${{ github.repository }}"
            git config --global user.email "<action@github.com>"
            git add .
            git commit --allow-empty -m "${MESSAGE}"
            git push origin master
          fi
